apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: eureka-discovery-service
  name: eureka-discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eureka-discovery-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/truyum-network: "true"
        io.kompose.service: eureka-discovery-service
    spec:
      containers:
      - image: harshverm776/eureka-discovery-server:0.0.1-SNAPSHOT
        imagePullPolicy: ""
        name: eureka-discovery-service
        ports:
        - containerPort: 8761
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
