apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: menuitem-service
  name: menuitem-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: menuitem-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/truyum-network: "true"
        io.kompose.service: menuitem-service
    spec:
      containers:
      - env:
        - name: EUREKA_HOST
          value: eureka-discovery-service
        image: harshverm776/menuitem-service:0.0.1-SNAPSHOT
        imagePullPolicy: ""
        name: menuitem-service
        ports:
        - containerPort: 8083
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
