apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: zuul-gateway
  name: zuul-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zuul-gateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/truyum-network: "true"
        io.kompose.service: zuul-gateway
    spec:
      containers:
      - env:
        - name: EUREKA_HOST
          value: eureka-discovery-service
        - name: MENU_HOST
          value: menuitem-service
        image: harshverm776/zuul-gateway:0.0.1-SNAPSHOT
        imagePullPolicy: ""
        name: zuul-gateway
        ports:
        - containerPort: 8085
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
